apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: nfs
spec:
  capacity:
     storage: 5Gi
  accessModes:
     - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /data
    server: 10.0.10.177

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  selector:
    matchLabels:
      type: "nfs"