- hosts: server
  remote_user: root
  tasks:
    - name: change hostname
      raw: "echo {{hostname|quote}} > /etc/hostname"
    - name:
      shell: hostname {{hostname|quote}}
    - name: install nginx
      shell: yum install -y nginx 
    - name: import ffmpeg repo
      shell: rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
    - name: download ffmpeg rpm
      shell: rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
    - name: install ffmpeg step3
      shell: yum install ffmpeg ffmpeg-devel -y
    - name: install php73 repo
      shell:  yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - name: yum install php73
      shell: yum -y install php73-php-fpm
    - name: start nginx
      shell: nginx -c /etc/nginx/nginx.conf
    - name: systemctl php73
      shell: systemctl enable php73-php-fpm && systemctl start php73-php-fpm
    